name: Deploy to server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env files
        shell: bash
        run: |
          # Создаем файлы именно в той папке, где лежит docker-compose.yml
          # Подставь правильный путь до папки с compose файлом
          DEST="Synapse/Synapse" 
          
          echo "${{ secrets.SCHEDULE }}" > "$DEST/.schedule.env"
          echo "${{ secrets.OTHER }}" > "$DEST/other.env"
          echo "${{ secrets.TGBOT }}" > "$DEST/.tg.bot.env"

      - name: Build and Deploy
        run: | 
          echo "Building and starting containers..."
          # Объединяем в одну команду для надежности
          docker compose up -d --build

      - name: Cleanup
        if: always() # Запускать даже если деплой упал
        run: |
          echo "Cleaning up..."
          rm -f .*.env
          docker image prune -f