name: Deploy to server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env files
        shell: bash
        run: |
          # Используем переменные окружения вместо прямой вставки секретов
          echo "${{ secrets.SCHEDULE }}" > .schedule.env
          echo "${{ secrets.OTHER }}" > .other.env
          echo "${{ secrets.TGBOT }}" > .tg.bot.env

      - name: Build and Deploy
        run: | 
          ls -a
          echo "Building and starting containers..."
          # Объединяем в одну команду для надежности
          docker compose up -d --build

      - name: Cleanup
        if: always() # Запускать даже если деплой упал
        run: |
          echo "Cleaning up..."
          rm -f .*.env
          docker system prune -f --volumes